# Generated by Django 6.0.4 on 2026-05-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="current_session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
