# Generated by Django 6.0.4 on 2026-05-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_enrollment_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_videos', to='users.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='users.video')),
            ],
        ),
    ]
