parts = []

parts.append('import { useState, useEffect } from "react"')
parts.append('import { Link, useNavigate } from "react-router-dom"')
parts.append('import { useAuth } from "../context/AuthContext"')
parts.append('import api from "../api/axios"')
parts.append('import {')
parts.append('  Play, BookOpen, Award, Clock, TrendingUp, Users, DollarSign, Star,')
parts.append('  ChevronRight, BarChart3, MoreHorizontal, CheckCircle2, Circle,')
parts.append('  GraduationCap, MonitorPlay, ShieldAlert')
parts.append('} from "lucide-react"')
parts.append('')

# CircularProgress component
parts.append('function CircularProgress({ percent, size = 80, stroke = 8 }) {')
parts.append('  const r = (size - stroke) / 2')
parts.append('  const c = 2 * Math.PI * r')
parts.append('  const offset = c - (percent / 100) * c')
parts.append('  return (')
parts.append('    <div className="relative inline-flex items-center justify-center" style={{ width: size, height: size }}>')
parts.append('      <svg width={size} height={size} className="-rotate-90">')
parts.append('        <circle cx={size/2} cy={size/2} r={r} stroke="#E2E8F0" strokeWidth={stroke} fill="none" />')
parts.append('        <circle cx={size/2} cy={size/2} r={r} stroke="#4F46E5" strokeWidth={stroke} fill="none"')
parts.append('          strokeDasharray={c} strokeDashoffset={offset} strokeLinecap="round" className="transition-all duration-700" />')
parts.append('      </svg>')
parts.append('      <span className="absolute text-sm font-bold text-text">{percent}%</span>')
parts.append('    </div>')
parts.append('  )')
parts.append('}')
parts.append('')

# StatCard component
parts.append('function StatCard({ icon: Icon, label, value, trend, color }) {')
parts.append('  const colorMap = {')
parts.append('    indigo: "bg-indigo-50 text-indigo-600",')
parts.append('    emerald: "bg-emerald-50 text-emerald-600",')
parts.append('    amber: "bg-amber-50 text-amber-600",')
parts.append('    rose: "bg-rose-50 text-rose-600",')
parts.append('  }')
parts.append('  return (')
parts.append('    <div className="bg-white rounded-2xl border border-border p-5 hover:shadow-sm transition">')
parts.append('      <div className="flex items-start justify-between">')
parts.append('        <div className={`p-2.5 rounded-xl ${colorMap[color] || colorMap.indigo}`}>')
parts.append('          <Icon className="w-5 h-5" />')
parts.append('        </div>')
parts.append('        {trend && <span className="text-xs font-medium text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full">{trend}</span>}')
parts.append('      </div>')
parts.append('      <p className="mt-3 text-2xl font-bold text-text">{value}</p>')
parts.append('      <p className="text-sm text-text-muted">{label}</p>')
parts.append('    </div>')
parts.append('  )')
parts.append('}')
parts.append('')

# Main Dashboard
parts.append('export default function Dashboard() {')
parts.append('  const { user } = useAuth()')
parts.append('  const navigate = useNavigate()')
parts.append('')

parts.append('  const renderRoleDashboard = () => {')
parts.append('    switch (user?.role) {')
parts.append('      case "admin": return <AdminDashboard />')
parts.append('      case "trainer": return <TrainerDashboard />')
parts.append('      default: return <StudentDashboard />')
parts.append('    }')
parts.append('  }')
parts.append('')

parts.append('  return (')
parts.append('    <div className="max-w-7xl mx-auto px-4 md:px-6 py-8">')
parts.append('      <div className="mb-8">')
parts.append('        <h1 className="text-2xl md:text-3xl font-bold text-text">Dashboard</h1>')
parts.append('        <p className="text-text-muted mt-1">')
parts.append('          Welcome back, <span className="font-medium text-text">{user?.first_name || user?.username}</span>')
parts.append('        </p>')
parts.append('      </div>')
parts.append('      {renderRoleDashboard()}')
parts.append('    </div>')
parts.append('  )')
parts.append('}')
parts.append('')

# StudentDashboard
parts.append('function StudentDashboard() {')
parts.append('  const [courses, setCourses] = useState([])')
parts.append('  const [progress, setProgress] = useState([])')
parts.append('  const [enrollments, setEnrollments] = useState([])')
parts.append('  const [loading, setLoading] = useState(true)')
parts.append('')

parts.append('  useEffect(() => {')
parts.append('    const fetchData = async () => {')
parts.append('      try {')
parts.append('        const [cRes, pRes, eRes] = await Promise.all([api.get("/courses/"), api.get("/progress/"), api.get("/enrollments/enrollments/")])')
parts.append('        setCourses(cRes.data.results || cRes.data || [])')
parts.append('        setProgress(pRes.data.results || pRes.data || [])')
parts.append('        setEnrollments(eRes.data.results || eRes.data || [])')
parts.append('      } catch { /* ignore */ } finally { setLoading(false) }')
parts.append('    }')
parts.append('    fetchData()')
parts.append('  }, [])')
parts.append('')

parts.append('  const enrolledCourses = courses.filter(c => enrollments.some(e => e.course === c.id))')
parts.append('  const totalLessons = enrolledCourses.reduce((sum, c) => sum + (c.lessons?.length || 0), 0)')
parts.append('  const completedLessons = progress.filter(p => p.is_completed).length')
parts.append('  const overallPercent = totalLessons > 0 ? Math.round((completedLessons / totalLessons) * 100) : 0')
parts.append('')

parts.append('  const continueCourse = enrolledCourses.find(c => {')
parts.append('    const lessons = c.lessons || []')
parts.append('    const completedIds = progress.filter(p => p.is_completed).map(p => p.lesson)')
parts.append('    return lessons.some(l => !completedIds.includes(l.id))')
parts.append('  })')
parts.append('')

parts.append('  const continueLesson = continueCourse ? (() => {')
parts.append('    const lessons = continueCourse.lessons || []')
parts.append('    const completedIds = progress.filter(p => p.is_completed).map(p => p.lesson)')
parts.append('    return lessons.find(l => !completedIds.includes(l.id)) || lessons[0]')
parts.append('  })() : null')
parts.append('')

parts.append('  const courseProgress = (course) => {')
parts.append('    const lessons = course.lessons || []')
parts.append('    if (!lessons.length) return 0')
parts.append('    const completedIds = progress.filter(p => p.is_completed).map(p => p.lesson)')
parts.append('    const done = lessons.filter(l => completedIds.includes(l.id)).length')
parts.append('    return Math.round((done / lessons.length) * 100)')
parts.append('  }')
parts.append('')

parts.append('  if (loading) return <div className="flex items-center justify-center h-64"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" /></div>')
parts.append('')

parts.append('  return (')
parts.append('    <div className="space-y-8">')
parts.append('      {/* Hero Stats */}')
parts.append('      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">')
parts.append('        <StatCard icon={BookOpen} label="Courses Enrolled" value={enrolledCourses.length} color="indigo" />')
parts.append('        <StatCard icon={CheckCircle2} label="Lessons Completed" value={completedLessons} color="emerald" />')
parts.append('        <StatCard icon={Clock} label="Hours Spent" value={Math.round(completedLessons * 0.5)} color="amber" />')
parts.append('        <StatCard icon={Award} label="Certificates" value={0} color="rose" />')
parts.append('      </div>')
parts.append('')

parts.append('      {/* Welcome + Overall Progress */}')
parts.append('      <div className="bg-white rounded-2xl border border-border p-6 md:p-8 flex flex-col md:flex-row items-center gap-6">')
parts.append('        <div className="flex-1">')
parts.append('          <h2 className="text-xl font-bold text-text">Keep up the great work!</h2>')
parts.append('          <p className="text-text-muted mt-2">You have completed {completedLessons} out of {totalLessons} lessons across all your enrolled courses.</p>')
parts.append('          <div className="mt-4 flex items-center gap-4">')
parts.append('            <Link to="/courses" className="inline-flex items-center gap-2 px-5 py-2.5 bg-primary text-white text-sm font-medium rounded-xl hover:bg-primary-dark transition">')
parts.append('              Browse Courses <ChevronRight className="w-4 h-4" />')
parts.append('            </Link>')
parts.append('          </div>')
parts.append('        </div>')
parts.append('        <div className="flex flex-col items-center gap-2">')
parts.append('          <CircularProgress percent={overallPercent} size={100} stroke={10} />')
parts.append('          <span className="text-sm font-medium text-text-muted">Overall Progress</span>')
parts.append('        </div>')
parts.append('      </div>')
parts.append('')

parts.append('      {/* Continue Learning */}')
parts.append('      {continueCourse && continueLesson && (')
parts.append('        <div className="bg-primary-light/50 rounded-2xl border border-primary/20 p-6">')
parts.append('          <div className="flex items-center gap-2 mb-3">')
parts.append('            <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse" />')
parts.append('            <span className="text-sm font-semibold text-primary uppercase tracking-wide">Continue Learning</span>')
parts.append('          </div>')
parts.append('          <div className="flex flex-col md:flex-row md:items-center gap-4">')
parts.append('            <div className="flex-1">')
parts.append('              <h3 className="text-lg font-bold text-text">{continueCourse.title}</h3>')
parts.append('              <p className="text-sm text-text-muted mt-1">Next: {continueLesson.title}</p>')
parts.append('              <div className="mt-3 flex items-center gap-3">')
parts.append('                <div className="flex-1 h-2 bg-slate-200 rounded-full overflow-hidden">')
parts.append('                  <div className="h-full bg-primary rounded-full transition-all" style={{ width: `${courseProgress(continueCourse)}%` }} />')
parts.append('                </div>')
parts.append('                <span className="text-xs font-medium text-text-muted">{courseProgress(continueCourse)}%</span>')
parts.append('              </div>')
parts.append('            </div>')
parts.append('            <Link to={`/courses/${continueCourse.id}`} className="inline-flex items-center gap-2 px-5 py-2.5 bg-primary text-white text-sm font-medium rounded-xl hover:bg-primary-dark transition shrink-0">')
parts.append('              <Play className="w-4 h-4" /> Resume')
parts.append('            </Link>')
parts.append('          </div>')
parts.append('        </div>')
parts.append('      )}')
parts.append('')

parts.append('      {/* Enrolled Courses Grid */}')
parts.append('      <div>')
parts.append('        <h3 className="text-lg font-bold text-text mb-4">My Courses</h3>')
parts.append('        {enrolledCourses.length === 0 ? (')
parts.append('          <div className="bg-white rounded-2xl border border-border p-8 text-center">')
parts.append('            <BookOpen className="w-10 h-10 text-text-muted mx-auto mb-3" />')
parts.append('            <p className="text-text-muted">No enrolled courses yet.</p>')
parts.append('            <Link to="/courses" className="inline-block mt-3 text-primary font-medium hover:underline">Browse Courses</Link>')
parts.append('          </div>')
parts.append('        ) : (')
parts.append('          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">')
parts.append('            {enrolledCourses.map((course) => (')
parts.append('              <div key={course.id} className="bg-white rounded-2xl border border-border overflow-hidden hover:shadow-sm transition group">')
parts.append('                <div className="h-32 bg-gradient-to-br from-primary/10 to-secondary/10 flex items-center justify-center">')
parts.append('                  <BookOpen className="w-10 h-10 text-primary/30" />')
parts.append('                </div>')
parts.append('                <div className="p-5">')
parts.append('                  <div className="flex items-center gap-2 mb-2">')
parts.append('                    <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-primary-light text-primary">{course.status || "Active"}</span>')
parts.append('                    <span className="text-xs text-text-muted flex items-center gap-1"><GraduationCap className="w-3 h-3" /> {course.trainer_name}</span>')
parts.append('                  </div>')
parts.append('                  <h4 className="font-semibold text-text mb-1 group-hover:text-primary transition">{course.title}</h4>')
parts.append('                  <p className="text-sm text-text-muted line-clamp-2 mb-3">{course.description || "No description"}</p>')
parts.append('                  <div className="flex items-center gap-3">')
parts.append('                    <div className="flex-1 h-1.5 bg-slate-100 rounded-full overflow-hidden">')
parts.append('                      <div className="h-full bg-emerald-500 rounded-full transition-all" style={{ width: `${courseProgress(course)}%` }} />')
parts.append('                    </div>')
parts.append('                    <span className="text-xs font-medium text-text-muted">{courseProgress(course)}%</span>')
parts.append('                  </div>')
parts.append('                  <Link to={`/courses/${course.id}`} className="inline-flex items-center gap-1 mt-4 text-sm font-medium text-primary hover:underline">')
parts.append('                    Continue <ChevronRight className="w-4 h-4" />')
parts.append('                  </Link>')
parts.append('                </div>')
parts.append('              </div>')
parts.append('            ))}')
parts.append('          </div>')
parts.append('        )}')
parts.append('      </div>')
parts.append('    </div>')
parts.append('  )')
parts.append('}')
parts.append('')

# TrainerDashboard
parts.append('function TrainerDashboard() {')
parts.append('  const [courses, setCourses] = useState([])')
parts.append('  const [enrollments, setEnrollments] = useState([])')
parts.append('  const [loading, setLoading] = useState(true)')
parts.append('')

parts.append('  useEffect(() => {')
parts.append('    const fetchData = async () => {')
parts.append('      try {')
parts.append('        const [cRes, eRes] = await Promise.all([api.get("/courses/"), api.get("/enrollments/enrollments/")])')
parts.append('        setCourses(cRes.data.results || cRes.data || [])')
parts.append('        setEnrollments(eRes.data.results || eRes.data || [])')
parts.append('      } catch { /* ignore */ } finally { setLoading(false) }')
parts.append('    }')
parts.append('    fetchData()')
parts.append('  }, [])')
parts.append('')

parts.append('  const myCourses = courses')
parts.append('  const totalStudents = enrollments.filter(e => myCourses.some(c => c.id === e.course)).length')
parts.append('  const activeCourses = myCourses.filter(c => c.status === "active").length')
parts.append('  const avgRating = 4.7')
parts.append('  const earnings = totalStudents * 49')
parts.append('')

parts.append('  if (loading) return <div className="flex items-center justify-center h-64"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" /></div>')
parts.append('')

parts.append('  return (')
parts.append('    <div className="space-y-8">')
parts.append('      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">')
parts.append('        <StatCard icon={Users} label="Total Students" value={totalStudents} trend="+12%" color="indigo" />')
parts.append('        <StatCard icon={BookOpen} label="Active Courses" value={activeCourses} color="emerald" />')
parts.append('        <StatCard icon={DollarSign} label="Total Earnings" value={`$${earnings}`} trend="+8%" color="amber" />')
parts.append('        <StatCard icon={Star} label="Avg. Rating" value={avgRating} color="rose" />')
parts.append('      </div>')
parts.append('')

parts.append('      <div className="bg-white rounded-2xl border border-border overflow-hidden">')
parts.append('        <div className="px-6 py-4 border-b border-border flex items-center justify-between">')
parts.append('          <h3 className="text-lg font-bold text-text">Manage Courses</h3>')
parts.append('          <button className="text-sm text-primary font-medium hover:underline">View All</button>')
parts.append('        </div>')
parts.append('        <div className="overflow-x-auto">')
parts.append('          <table className="w-full text-sm text-left">')
parts.append('            <thead className="bg-slate-50 text-text-muted uppercase text-xs">')
parts.append('              <tr>')
parts.append('                <th className="px-6 py-3 font-medium">Course</th>')
parts.append('                <th className="px-6 py-3 font-medium">Students</th>')
parts.append('                <th className="px-6 py-3 font-medium">Status</th>')
parts.append('                <th className="px-6 py-3 font-medium">Rating</th>')
parts.append('                <th className="px-6 py-3 font-medium text-right">Actions</th>')
parts.append('              </tr>')
parts.append('            </thead>')
parts.append('            <tbody className="divide-y divide-border">')
parts.append('              {myCourses.map((course) => {')
parts.append('                const students = enrollments.filter(e => e.course === course.id).length')
parts.append('                return (')
parts.append('                  <tr key={course.id} className="hover:bg-slate-50 transition">')
parts.append('                    <td className="px-6 py-4 font-medium text-text">{course.title}</td>')
parts.append('                    <td className="px-6 py-4 text-text-muted">{students}</td>')
parts.append('                    <td className="px-6 py-4">')
parts.append('                      <span className={`text-xs font-medium px-2.5 py-1 rounded-full ${course.status === "active" ? "bg-emerald-50 text-emerald-600" : "bg-amber-50 text-amber-600"}`}>')
parts.append('                        {course.status === "active" ? "Published" : "Draft"}')
parts.append('                      </span>')
parts.append('                    </td>')
parts.append('                    <td className="px-6 py-4 text-text-muted flex items-center gap-1"><Star className="w-3.5 h-3.5 text-amber-400 fill-amber-400" /> 4.7</td>')
parts.append('                    <td className="px-6 py-4 text-right">')
parts.append('                      <Link to={`/courses/${course.id}`} className="text-primary font-medium hover:underline">Edit</Link>')
parts.append('                    </td>')
parts.append('                  </tr>')
parts.append('                )')
parts.append('              })}')
parts.append('              {myCourses.length === 0 && (')
parts.append('                <tr><td colSpan={5} className="px-6 py-8 text-center text-text-muted">No courses yet.</td></tr>')
parts.append('              )}')
parts.append('            </tbody>')
parts.append('          </table>')
parts.append('        </div>')
parts.append('      </div>')
parts.append('    </div>')
parts.append('  )')
parts.append('}')
parts.append('')

# AdminDashboard
parts.append('function AdminDashboard() {')
parts.append('  const [courses, setCourses] = useState([])')
parts.append('  const [enrollments, setEnrollments] = useState([])')
parts.append('  const [loading, setLoading] = useState(true)')
parts.append('')

parts.append('  useEffect(() => {')
parts.append('    const fetchData = async () => {')
parts.append('      try {')
parts.append('        const [cRes, eRes] = await Promise.all([api.get("/courses/"), api.get("/enrollments/enrollments/")])')
parts.append('        setCourses(cRes.data.results || cRes.data || [])')
parts.append('        setEnrollments(eRes.data.results || eRes.data || [])')
parts.append('      } catch { /* ignore */ } finally { setLoading(false) }')
parts.append('    }')
parts.append('    fetchData()')
parts.append('  }, [])')
parts.append('')

parts.append('  const totalStudents = enrollments.length')
parts.append('  const totalCourses = courses.length')
parts.append('  const activeCourses = courses.filter(c => c.status === "active").length')
parts.append('')

parts.append('  if (loading) return <div className="flex items-center justify-center h-64"><div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" /></div>')
parts.append('')

parts.append('  return (')
parts.append('    <div className="space-y-8">')
parts.append('      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">')
parts.append('        <StatCard icon={Users} label="Total Students" value={totalStudents} color="indigo" />')
parts.append('        <StatCard icon={BookOpen} label="Total Courses" value={totalCourses} color="emerald" />')
parts.append('        <StatCard icon={MonitorPlay} label="Active Courses" value={activeCourses} color="amber" />')
parts.append('        <StatCard icon={ShieldAlert} label="Pending Reviews" value={0} color="rose" />')
parts.append('      </div>')
parts.append('')

parts.append('      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">')
parts.append('        <div className="bg-white rounded-2xl border border-border p-6">')
parts.append('          <h3 className="text-lg font-bold text-text mb-4">Quick Actions</h3>')
parts.append('          <div className="grid grid-cols-2 gap-3">')
parts.append('            <Link to="/courses" className="p-4 rounded-xl bg-primary-light text-primary font-medium text-center hover:bg-primary/20 transition">Manage Courses</Link>')
parts.append('            <div className="p-4 rounded-xl bg-slate-50 text-text-muted font-medium text-center cursor-not-allowed">User Management</div>')
parts.append('            <div className="p-4 rounded-xl bg-slate-50 text-text-muted font-medium text-center cursor-not-allowed">Reports</div>')
parts.append('            <div className="p-4 rounded-xl bg-slate-50 text-text-muted font-medium text-center cursor-not-allowed">Settings</div>')
parts.append('          </div>')
parts.append('        </div>')
parts.append('        <div className="bg-white rounded-2xl border border-border p-6">')
parts.append('          <h3 className="text-lg font-bold text-text mb-4">Platform Overview</h3>')
parts.append('          <div className="space-y-3">')
parts.append('            <div className="flex items-center justify-between text-sm">')
parts.append('              <span className="text-text-muted">Course Completion Rate</span>')
parts.append('              <span className="font-medium text-text">68%</span>')
parts.append('            </div>')
parts.append('            <div className="h-2 bg-slate-100 rounded-full overflow-hidden"><div className="h-full bg-primary rounded-full" style={{ width: "68%" }} /></div>')
parts.append('            <div className="flex items-center justify-between text-sm">')
parts.append('              <span className="text-text-muted">Student Satisfaction</span>')
parts.append('              <span className="font-medium text-text">4.7/5</span>')
parts.append('            </div>')
parts.append('            <div className="h-2 bg-slate-100 rounded-full overflow-hidden"><div className="h-full bg-emerald-500 rounded-full" style={{ width: "94%" }} /></div>')
parts.append('          </div>')
parts.append('        </div>')
parts.append('      </div>')
parts.append('    </div>')
parts.append('  )')
parts.append('}')

with open(r'c:/Users/Manjunath C H/OneDrive/Pictures/lms_mca/frontend/src/pages/Dashboard.jsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(parts))

print('Dashboard.jsx written, lines:', len(parts))
