parts = []

parts.append('import { useState, useEffect } from "react"')
parts.append('import { useParams, useNavigate } from "react-router-dom"')
parts.append('import { useAuth } from "../context/AuthContext"')
parts.append('import api from "../api/axios"')
parts.append('import {')
parts.append('  Play, Pause, CheckCircle2, Circle, ChevronLeft, ChevronRight,')
parts.append('  Clock, FileText, Download, Loader2, Award')
parts.append('} from "lucide-react"')
parts.append('')

# getYoutubeEmbedUrl helper
parts.append('function getYoutubeEmbedUrl(url) {')
parts.append('  if (!url) return null')
parts.append('  const match = url.match(/(?:youtube\\.com\\/watch\\?v=|youtu\\.be\\/)([a-zA-Z0-9_-]+)/)')
parts.append('  return match ? `https://www.youtube.com/embed/${match[1]}?controls=1&modestbranding=1&rel=0` : null')
parts.append('}')
parts.append('')

# CircularProgress
parts.append('function CircularProgress({ percent, size = 48, stroke = 5 }) {')
parts.append('  const r = (size - stroke) / 2')
parts.append('  const c = 2 * Math.PI * r')
parts.append('  const offset = c - (percent / 100) * c')
parts.append('  return (')
parts.append('    <div className="relative inline-flex items-center justify-center" style={{ width: size, height: size }}>')
parts.append('      <svg width={size} height={size} className="-rotate-90">')
parts.append('        <circle cx={size/2} cy={size/2} r={r} stroke="#E2E8F0" strokeWidth={stroke} fill="none" />')
parts.append('        <circle cx={size/2} cy={size/2} r={r} stroke="#4F46E5" strokeWidth={stroke} fill="none"')
parts.append('          strokeDasharray={c} strokeDashoffset={offset} strokeLinecap="round" className="transition-all duration-700" />')
parts.append('      </svg>')
parts.append('      <span className="absolute text-[10px] font-bold text-text">{percent}%</span>')
parts.append('    </div>')
parts.append('  )')
parts.append('}')
parts.append('')

# Main CoursePlayer
parts.append('export default function CoursePlayer() {')
parts.append('  const { id } = useParams()')
parts.append('  const navigate = useNavigate()')
parts.append('  const { user } = useAuth()')
parts.append('  const [course, setCourse] = useState(null)')
parts.append('  const [progress, setProgress] = useState([])')
parts.append('  const [activeLessonId, setActiveLessonId] = useState(null)')
parts.append('  const [loading, setLoading] = useState(true)')
parts.append('  const [marking, setMarking] = useState(false)')
parts.append('  const [error, setError] = useState("")')
parts.append('')

parts.append('  useEffect(() => {')
parts.append('    if (!id) return')
parts.append('    fetchCourse()')
parts.append('    if (user?.role === "student") fetchProgress()')
parts.append('  }, [id, user])')
parts.append('')

parts.append('  const fetchCourse = async () => {')
parts.append('    try {')
parts.append('      setLoading(true)')
parts.append('      const res = await api.get(`/courses/${id}/`)')
parts.append('      const data = res.data')
parts.append('      setCourse(data)')
parts.append('      const lessons = data.lessons || []')
parts.append('      if (lessons.length > 0 && !activeLessonId) setActiveLessonId(lessons[0].id)')
parts.append('    } catch (err) {')
parts.append('      setError("Failed to load course")')
parts.append('    } finally {')
parts.append('      setLoading(false)')
parts.append('    }')
parts.append('  }')
parts.append('')

parts.append('  const fetchProgress = async () => {')
parts.append('    try {')
parts.append('      const res = await api.get("/progress/")')
parts.append('      setProgress(res.data.results || res.data || [])')
parts.append('    } catch { /* ignore */ }')
parts.append('  }')
parts.append('')

parts.append('  const markComplete = async (lessonId) => {')
parts.append('    if (!lessonId) return')
parts.append('    try {')
parts.append('      setMarking(true)')
parts.append('      await api.post("/progress/", { lesson: lessonId, is_completed: true })')
parts.append('      fetchProgress()')
parts.append('    } catch (err) {')
parts.append('      alert(err.response?.data?.detail || "Failed to update progress")')
parts.append('    } finally {')
parts.append('      setMarking(false)')
parts.append('    }')
parts.append('  }')
parts.append('')

parts.append('  const isCompleted = (lessonId) => progress.some((p) => p.lesson === lessonId && p.is_completed)')
parts.append('')

parts.append('  const lessons = course?.lessons || []')
parts.append('  const totalLessons = lessons.length')
parts.append('  const completedCount = lessons.filter((l) => isCompleted(l.id)).length')
parts.append('  const progressPercent = totalLessons > 0 ? Math.round((completedCount / totalLessons) * 100) : 0')
parts.append('')

parts.append('  const activeLesson = lessons.find((l) => l.id === activeLessonId) || lessons[0]')
parts.append('  const activeIndex = lessons.findIndex((l) => l.id === activeLessonId)')
parts.append('  const prevLesson = activeIndex > 0 ? lessons[activeIndex - 1] : null')
parts.append('  const nextLesson = activeIndex < lessons.length - 1 ? lessons[activeIndex + 1] : null')
pa
