parts = []

parts.append('import { useState, useRef, useEffect } from "react"')
parts.append('import { Outlet, Link, useLocation, useNavigate } from "react-router-dom"')
parts.append('import { useAuth } from "../context/AuthContext"')
parts.append('import { LayoutDashboard, BookOpen, BarChart3, Settings, Search, Bell, ChevronLeft, ChevronRight, Menu, X, LogOut, User, GraduationCap, Shield, MonitorPlay } from "lucide-react"')
parts.append('')

parts.append('const NAV_ITEMS = [')
parts.append('  { label: "Dashboard", icon: LayoutDashboard, href: "/" },')
parts.append('  { label: "Courses", icon: BookOpen, href: "/courses" },')
parts.append('  { label: "Analytics", icon: BarChart3, href: "#" },')
parts.append('  { label: "Settings", icon: Settings, href: "#" },')
parts.append(']')
parts.append('')

parts.append('const ROLE_META = {')
parts.append('  student: { icon: GraduationCap, label: "Student", color: "text-emerald-600 bg-emerald-50" },')
parts.append('  trainer: { icon: MonitorPlay, label: "Trainer", color: "text-indigo-600 bg-indigo-50" },')
parts.append('  admin: { icon: Shield, label: "Admin", color: "text-rose-600 bg-rose-50" },')
parts.append('}')
parts.append('')

parts.append('export default function Layout() {')
parts.append('  const { user, logout } = useAuth()')
parts.append('  const navigate = useNavigate()')
parts.append('  const location = useLocation()')
parts.append('  const [collapsed, setCollapsed] = useState(false)')
parts.append('  const [mobileOpen, setMobileOpen] = useState(false)')
parts.append('  const [searchQuery, setSearchQuery] = useState("")')
parts.append('  const [showProfile, setShowProfile] = useState(false)')
parts.append('  const profileRef = useRef(null)')
parts.append('')

parts.append('  useEffect(() => {')
parts.append('    const handler = (e) => { if (profileRef.current && !profileRef.current.contains(e.target)) setShowProfile(false) }')
parts.append('    document.addEventListener("mousedown", handler)')
parts.append('    return () => document.removeEventListener("mousedown", handler)')
parts.append('  }, [])')
parts.append('')

parts.append('  const doLogout = () => { logout(); navigate("/login") }')
parts.append('  const doSearch = (e) => {')
parts.append('    e.preventDefault()')
parts.append('    if (searchQuery.trim()) { navigate(`/courses?search=${encodeURIComponent(searchQuery.trim())}`); setSearchQuery("") }')
parts.append('  }')
parts.append('')

parts.append('  const roleMeta = ROLE_META[user?.role] || ROLE_META.student')
parts.append('  const RoleIcon = roleMeta.icon')
parts.append('')

parts.append('  const navLinkClass = (active) => active')
parts.append('    ? "flex items-center gap-3 px-3 py-2.5 rounded-xl bg-primary-light text-primary font-medium transition"')
parts.append('    : "flex items-center gap-3 px-3 py-2.5 rounded-xl text-text-muted hover:bg-slate-100 hover:text-text transition"')
parts.append('')

parts.append('  return (')
parts.append('    <div className="min-h-screen bg-bg flex text-text">')
parts.append('      {mobileOpen && <div className="fixed inset-0 bg-black/30 z-40 md:hidden" onClick={() => setMobileOpen(false)} />}')

parts.append('      <aside className={`fixed md:sticky top-0 left-0 z-50 h-screen bg-surface border-r border-border flex flex-col transition-all duration-300 ${mobileOpen ? "translate-x-0" : "-translate-x-full md:translate-x-0"} ${collapsed ? "w-[72px]" : "w-64"}`}>')
parts.append('        <div className="h-16 flex items-center px-4 border-b border-border">')
parts.append('          <Link to="/" className="flex items-center gap-2">')
parts.append('            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center shrink-0">')
parts.append('              <BookOpen className="w-5 h-5 text-white" />')
parts.append('            </div>')
parts.append('            {!collapsed && <span className="font-bold text-lg tracking-tight">LearnHub</span>}')
parts.append('          </Link>')
parts.append('          <button onClick={() => setMobileOpen(false)} className="md:hidden ml-auto p-1 rounded-md hover:bg-slate-100">')
parts.append('            <X className="w-5 h-5 text-text-muted" />')
parts.append('          </button>')
parts.append('        </div>')

parts.append('        <nav className="flex-1 overflow-y-auto py-4 px-3 space-y-1">')
parts.append('          {NAV_ITEMS.map((item) => {')
parts.append('            const isActive = location.pathname === item.href || (item.href !== "/" && location.pathname.startsWith(item.href))')
parts.append('            const Icon = item.icon')
parts.append('            return (')
parts.append('              <Link key={item.label} to={item.href} onClick={() => setMobileOpen(false)} className={navLinkClass(isActive)} title={collapsed ? item.label : undefined}>')
parts.append('                <Icon className={`w-5 h-5 shrink-0 ${isActive ? "text-primary" : ""}`} />')
parts.append('                {!collapsed && <span className="text-sm whitespace-nowrap">{item.label}</span>}')
parts.append('              </Link>')
parts.append('            )')
parts.append('          })}')
parts.append('        </nav>')

parts.append('        <div className="p-3 border-t border-border">')
parts.append('          <button onClick={() => setCollapsed(!collapsed)} className="hidden md:flex w-full items-center justify-center gap-2 px-3 py-2 text-xs font-medium text-text-muted hover:text-text hover:bg-slate-100 rounded-xl transition">')
parts.append('            {collapsed ? <ChevronRight className="w-4 h-4" /> : <><ChevronLeft className="w-4 h-4" /><span>Collapse</span></>}')
parts.append('          </button>')
parts.append('        </div>')
parts.append('      </aside>')

parts.append('      <div className="flex-1 flex flex-col min-w-0">')
parts.append('        <header className="sticky top-0 z-30 bg-white/80 backdrop-blur-md border-b border-border">')
parts.append('          <div className="h-16 px-4 md:px-6 flex items-center justify-between gap-4">')
parts.append('            <div className="flex items-center gap-3 flex-1">')
parts.append('              <button onClick={() => setMobileOpen(true)} className="md:hidden p-2 rounded-lg hover:bg-slate-100 text-text-muted">')
parts.append('                <Menu className="w-5 h-5" />')
parts.append('              </button>')
parts.append('              <form onSubmit={doSearch} className="relative max-w-md w-full hidden sm:block">')
parts.append('                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted pointer-events-none" />')
parts.append('                <input type="text" value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="Search courses, lessons..." className="w-full pl-9 pr-4 py-2 text-sm rounded-xl border border-border bg-slate-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition" />')
parts.append('              </form>')
parts.append('            </div>')

parts.append('            <div className="flex items-center gap-2 md:gap-4">')
parts.append('              <button className="relative p-2 rounded-xl hover:bg-slate-100 text-text-muted transition">')
parts.append('                <Bell className="w-5 h-5" />')
parts.append('                <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-red-500 rounded-full ring-2 ring-white" />')
parts.append('              </button>')

parts.append('              <div className="relative" ref={profileRef}>')
parts.append('                <button onClick={() => setShowProfile(!showProfile)} className="flex items-center gap-2 md:gap-3 pl-2 pr-3 py-1.5 rounded-xl hover:bg-slate-100 transition">')
parts.append('                  <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold text-sm">')
parts.append('                    {user?.first_name?.[0] || user?.username?.[0] || "U"}')
parts.append('                  </div>')
parts.append('                  <div className="hidden md:block text-left min-w-0">')
parts.append('                    <p className="text-sm font-medium leading-tight truncate">{user?.first_name || user?.username}</p>')
parts.append('                    <p className="text-xs text-text-muted capitalize">{user?.role}</p>')
parts.append('                  </div>')
parts.append('                </button>')

parts.append('                {showProfile && (')
parts.append('                  <div className="absolute right-0 mt-2 w-64 bg-white rounded-2xl shadow-lg border border-border overflow-hidden z-50">')
parts.append('                    <div className="px-4 py-3 border-b border-border">')
parts.append('                      <p className="text-sm font-semibold text-text">{user?.first_name || user?.username} {user?.last_name || ""}</p>')
parts.append('                      <p className="text-xs text-text-muted">{user?.email}</p>')
parts.append('                      <span className={`inline-flex items-center gap-1 mt-2 text-xs font-medium px-2 py-0.5 rounded-full ${roleMeta.color}`}>')
parts.append('                        <RoleIcon className="w-3 h-3" /> {roleMeta.label}')
parts.append('                      </span>')
parts.append('                    </div>')
parts.append('                    <div className="py-1">')
parts.append('                      <button onClick={() => { setShowProfile(false); navigate("/") }} className="w-full flex items-center gap-2 px-4 py-2 text-sm text-text-muted hover:bg-slate-50 hover:text-text transition">')
parts.append('                        <User className="w-4 h-4" /> Profile')
parts.append('                      </button>')
parts.append('                      <button onClick={doLogout} className="w-full flex items-center gap-2 px-4 py-2 text-sm text-red-600 hover:bg-red-50 transition">')
parts.append('                        <LogOut className="w-4 h-4" /> Logout')
parts.append('                      </button>')
parts.append('                    </div>')
parts.append('                  </div>')
parts.append('                )}')
parts.append('              </div>')
parts.append('            </div>')
parts.append('          </div>')
parts.append('        </header>')

parts.append('        <main className="flex-1 overflow-y-auto">')
parts.append('          <Outlet />')
parts.append('        </main>')
parts.append('      </div>')
parts.append('    </div>')
parts.append('  )')
parts.append('}')

with open(r'c:/Users/Manjunath C H/OneDrive/Pictures/lms_mca/frontend/src/components/Layout.jsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(parts))

print('Done:', len(parts), 'lines')
