# Generated by Django 6.0.4 on 2026-04-23 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsm', '0004_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsm.course')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
