# Generated by Django 6.0.4 on 2026-04-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsm', '0005_course_trainer_alter_course_table_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_url',
        ),
    ]
