# Generated by Django 6.0.4 on 2026-04-23 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsm', '0006_remove_course_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, to='lsm.course'),
        ),
    ]
