# Generated by Django 6.0.4 on 2026-04-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='session_key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('trainer', 'Trainer'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
