# Generated by Django 6.0.4 on 2026-05-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
