# Generated by Django 6.0.4 on 2026-04-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active')], default='upcoming', max_length=10),
        ),
    ]
