# Generated by Django 6.0.3 on 2026-04-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
