# Generated by Django 4.2 on 2026-04-26 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to=settings.AUTH_USER_MODEL, verbose_name='enrolled by'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('enrollment', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'is_active'], name='courses_enr_user_id_b47998_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'is_active'], name='courses_enr_course__4313b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'created_at'], name='courses_cou_status_ed6868_idx'),
        ),
    ]
