# Generated by Django 6.0.4 on 2026-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
