# Generated by Django 6.0.4 on 2026-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_active_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
