# Generated by Django 6.0.4 on 2026-05-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='login_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='session_key',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
