# Generated by Django 5.2.13 on 2026-04-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('trainer', 'Trainer'), ('student', 'Student')], default='student', help_text='Determines what the user is allowed to do in the LMS.', max_length=10),
        ),
    ]
