# Generated by Django 6.0.4 on 2026-05-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_remove_course_created_at_remove_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='Introduction Video', max_length=200),
            preserve_default=False,
        ),
    ]
