# Generated by Django 4.2.30 on 2026-04-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20),
        ),
    ]
