# Generated by Django 4.2.30 on 2026-05-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_activesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='token',
            field=models.TextField(),
        ),
    ]
