# Generated by Django 6.0.4 on 2026-04-22 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="progress",
            unique_together={("student", "video")},
        ),
    ]
