/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrainerVideosRouteImport } from './routes/trainer.videos'
import { Route as TrainerCoursesRouteImport } from './routes/trainer.courses'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as StudentCourseCourseIdRouteImport } from './routes/student.course.$courseId'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrainerVideosRoute = TrainerVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerCoursesRoute = TrainerCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TrainerRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const StudentCourseCourseIdRoute = StudentCourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/trainer': typeof TrainerRouteWithChildren
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/courses': typeof StudentCoursesRoute
  '/trainer/courses': typeof TrainerCoursesRoute
  '/trainer/videos': typeof TrainerVideosRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/login': typeof LoginRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/courses': typeof StudentCoursesRoute
  '/trainer/courses': typeof TrainerCoursesRoute
  '/trainer/videos': typeof TrainerVideosRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/trainer': typeof TrainerIndexRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/trainer': typeof TrainerRouteWithChildren
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/courses': typeof StudentCoursesRoute
  '/trainer/courses': typeof TrainerCoursesRoute
  '/trainer/videos': typeof TrainerVideosRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/student/course/$courseId': typeof StudentCourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courses'
    | '/login'
    | '/student'
    | '/trainer'
    | '/admin/courses'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/trainer/courses'
    | '/trainer/videos'
    | '/admin/'
    | '/student/'
    | '/trainer/'
    | '/student/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/login'
    | '/admin/courses'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/trainer/courses'
    | '/trainer/videos'
    | '/admin'
    | '/student'
    | '/trainer'
    | '/student/course/$courseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courses'
    | '/login'
    | '/student'
    | '/trainer'
    | '/admin/courses'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/users'
    | '/student/courses'
    | '/trainer/courses'
    | '/trainer/videos'
    | '/admin/'
    | '/student/'
    | '/trainer/'
    | '/student/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoursesRoute: typeof CoursesRoute
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  TrainerRoute: typeof TrainerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trainer/videos': {
      id: '/trainer/videos'
      path: '/videos'
      fullPath: '/trainer/videos'
      preLoaderRoute: typeof TrainerVideosRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/courses': {
      id: '/trainer/courses'
      path: '/courses'
      fullPath: '/trainer/courses'
      preLoaderRoute: typeof TrainerCoursesRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/course/$courseId': {
      id: '/student/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/student/course/$courseId'
      preLoaderRoute: typeof StudentCourseCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCourseCourseIdRoute: typeof StudentCourseCourseIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCoursesRoute: StudentCoursesRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCourseCourseIdRoute: StudentCourseCourseIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TrainerRouteChildren {
  TrainerCoursesRoute: typeof TrainerCoursesRoute
  TrainerVideosRoute: typeof TrainerVideosRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerCoursesRoute: TrainerCoursesRoute,
  TrainerVideosRoute: TrainerVideosRoute,
  TrainerIndexRoute: TrainerIndexRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CoursesRoute: CoursesRoute,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  TrainerRoute: TrainerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
