# Generated by Django 6.0.4 on 2026-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
