# Generated by Django 6.0.4 on 2026-05-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_course_coursevideo_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("ADVANCED", "Advanced"),
                ],
                default="BEGINNER",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.URLField(
                blank=True, help_text="URL to course thumbnail image", null=True
            ),
        ),
    ]
