# Generated by Django 6.0.4 on 2026-05-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_course_difficulty_level_course_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.URLField(
                blank=True,
                help_text="URL to course thumbnail image",
                max_length=2000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coursevideo",
            name="youtube_url",
            field=models.URLField(max_length=2000),
        ),
    ]
