# Generated by Django 6.0.4 on 2026-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_course_thumbnail_alter_coursevideo_youtube_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.TextField(
                blank=True,
                help_text="URL or Base64 data for course thumbnail image",
                null=True,
            ),
        ),
    ]
