# Generated by Django 6.0.4 on 2026-05-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_course_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_by',
            new_name='trainer',
        ),
    ]
