# Generated by Django 6.0.5 on 2026-05-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_issued',
            field=models.BooleanField(default=False),
        ),
    ]
