# Generated by Django 6.0.5 on 2026-05-13 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollment', '0003_alter_enrollment_options_enrollment_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course'], name='enrollment__student_de5864_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['completed', 'completed_at'], name='enrollment__complet_1eb223_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['last_accessed'], name='enrollment__last_ac_67d8ef_idx'),
        ),
    ]
