# Generated by Django 6.0.5 on 2026-05-15 04:20

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def mark_existing_enrollments_approved(apps, schema_editor):
    Enrollment = apps.get_model('enrollment', 'Enrollment')
    Enrollment.objects.filter(status='pending').update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollment', '0004_enrollment_enrollment__student_de5864_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(mark_existing_enrollments_approved, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status', 'requested_at'], name='enrollment__status_34e486_idx'),
        ),
    ]
