# Generated by Django 6.0.4 on 2026-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_enrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
