# Generated by Django 6.0.4 on 2026-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_user_active_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('trainer', 'Trainer'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
