# Generated by Django 6.0.4 on 2026-04-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='time_watched',
            field=models.FloatField(default=0),
        ),
    ]
