# Generated by Django 6.0.4 on 2026-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
