# Generated by Django 6.0.3 on 2026-04-23 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[('python', 'Python'), ('sql', 'SQL'), ('java', 'Java'), ('django', 'Django')], max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
