# Generated by Django 6.0.4 on 2026-04-26 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=10, verbose_name='device type')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='browser')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='operating system')),
                ('access_token', models.CharField(blank=True, max_length=100, verbose_name='access token ref')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='login time')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='last activity')),
                ('logged_out_at', models.DateTimeField(blank=True, null=True, verbose_name='logout time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='lms_session_user_id_756621_idx'), models.Index(fields=['ip_address'], name='lms_session_ip_addr_428e54_idx'), models.Index(fields=['created_at'], name='lms_session_created_3229c6_idx')],
            },
        ),
    ]
