# Generated by Django 6.0.4 on 2026-05-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_securitynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='video_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
