# Generated by Django 6.0.4 on 2026-04-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='session_key',
        ),
        migrations.AddField(
            model_name='usersession',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
