# Generated by Django 6.0.4 on 2026-04-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_usersession_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='active_session_key',
        ),
        migrations.AddField(
            model_name='user',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
