# Generated by Django 6.0.3 on 2026-05-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
